services:
  - type: web
    name: bcm4staratlas
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    rootDir: .
    buildCommand: npm run build
    startCommand: node .output/server/index.mjs
    autoDeployTrigger: commit
    envVars:
      - key: RENDER
        value: "true"
